language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "nightly"

dist: trusty
sudo: required

env: CPPFLAGS="--std=c++11"

addons:
  apt:
    packages:
    - libpng-dev
    - build-essential

install:
    - pip install pytest
    - pip install .

script: pytest -v

